tasks:
  - name: Terminal 1
  - init: |
          npm i -g @angular/cli
          cd ./vitrine/
          npm install
  - name: Terminal 2
  - init: cd ./vitrine/
ports:
  - port: 4200
    onOpen: open-preview